### PR TITLE
Step-1_Completed_Imported-and-Read-app-data

### PR DESCRIPTION
**Pull request by aarpit1010**
#7 

Changes: App data has been imported & read successfully from the given dataset.

### CODE REVIEW

**Comment by aarpit1010** [comment]
@adinalini  could you please check now whether my PR is correct or not.

Thank you

**Comment by adinalini** [comment]
Yup the code looks correct 👍 You can now comment on the second issue to get assigned.

**Comment by aarpit1010** [comment]
@adinalini could you please put the label hacktoberfest-accepted for this PR

**Comment by adinalini** [comment]
@aarpit1010 There's no need for that, it's already merged and the repo has the hacktoberfest label

**Pull request merged**
