### PR TITLE
Feature creation

### PR DESCRIPTION
**Pull request by anushavc**
this is my solution to issue #10

### CODE REVIEW

**Review by adinalini — CHANGES_REQUESTED** [review]
Anusha, you are on the right path! Dropping unnecessary columns is one step of feature creation. Feature creation also involves normalization of data to be later used as inputs for the model.

This article might help you: https://towardsdatascience.com/automated-feature-engineering-in-python-99baf11cc219

**Comment by adinalini** [comment]
If you are stuck, you can ask for help

**Comment by anushavc** [comment]
hey i added 3 more commits.Could you once check if it is okay rn?

**Comment by adinalini** [comment]
The code seems correct anusha, try printing the encoded values of application_record to verify once, I will merge it then 👍

**Comment by anushavc** [comment]
okay sure

**Comment by anushavc** [comment]
Is it okay now?

**Review by adinalini — CHANGES_REQUESTED** [review]
Yep everything is correct, one last thing though. The values for AMT_INCOME_TOTAL are highly variable, it is suggested to use log here (read more here: https://stats.stackexchange.com/questions/18844/when-and-why-should-you-take-the-log-of-a-distribution-of-numbers).

Basically your model will train on absolute difference instead of relative difference. (If you don't take log)

**Comment by anushavc** [comment]
made the change

**Comment by adinalini** [comment]
Awesome @anushavc 👍 You can now start working on the next issue :)

**Pull request merged**
