### PR TITLE
Imported and read app data

### PR DESCRIPTION
**Pull request by anushavc**
This is my solution to issue #7

### CODE REVIEW

**Comment by adinalini** [comment]
Anusha, the code is correct! But you have to comment on the respective issue first, asking to be assigned the task.

**Comment by anushavc** [comment]
oh i am so sorry, didnt know about that.

**Comment by anushavc** [comment]
Can i comment now on the issue?

**Comment by adinalini** [comment]
Yeah

**Comment by adinalini** [comment]
Leave it this time ig, do it from next issue

**Comment by adinalini** [comment]
Comment when starting 2nd task

**Pull request merged**
