### PR TITLE
Added PR and ISSUE template (Doubt)

### PR DESCRIPTION
**Pull request by adinalini**
Added .github folder and ISSUE template to ask for doubts. Also added contributing guidelines.md

### CODE REVIEW

**Comment by eeshashetty** [comment]
Okay so instead of making all these separate files, compile everything and update the README, like i said
- For the issue description format, I've already mentioned the guidelines under README with the proper format
- Almost everything you've made multiple files for has already been written in readme. Please read through it first and make additions/changes there. For reference check out the readme on the other research projects
- For doubts, people can directly comment on the issues you post, so don't create that file

I'm not closing this PR, just delete all these extra files on your branch, make changes **only** in the README, and commit that. I'll merge it then.

**Comment by adinalini** [comment]
I have removed all the repeated files, should I remove all of this and add it to readme instead?

**Comment by eeshashetty** [comment]
yep perfect. Make all those changes to the README, also including a section on how to use the helper file to create issues

**Comment by adinalini** [comment]
Alright, on it

**Comment by adinalini** [comment]
Done @eeshashetty

**Comment by adinalini** [comment]
Oh no! The bot deleted all my files! WHYYYYY :(

**Comment by adinalini** [comment]
Alright @eeshashetty Ready to be merged :)

**Pull request merged**
